In [1]:
import sys
import os

sys.path.append(os.path.abspath("../src"))

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/car_rental_raw.csv")

df.head()

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_TS,Pickup_TS,Return_TS,City,Pickup_Lat,Pickup_Lon,...,Harsh_Events,Damage_Flag,Rate,Promo_Code,GST_Amount,Total_Amount,Rate_Plan,Driver_License,Notes,Customer_Feedback
0,RES-00001,C1434,car-18,Luxury,2026-03-22 13:01,23-03-2026 03:01,2026-03-24 18:01,Kolkata,22.576220,88.345171,...,3,0,1500/day,BOGUS99,75.0,1575.0,standard,INVALID,Scratch on windows,Good mileage
1,RES-00002,C2584,CAR-12,SUV,2026-02-25 11:17,2026/02/27 18:17,2026-03-01 14:17,delhi,28.690319,77.120789,...,2,0,800,NaN,NaN,840.0,standard,INVALID,Bad Seats Quality,Good mileage
2,RES-00003,C2307,car-28,Economy,2026-02-26 18:07,2026-02-28 17:07:00,2026-03-04 00:07,Chennai,13.090883,80.252533,...,5,0,2500,BOGUS99,NaN,2625.0,eco,DL12345,scratch on door,Good mileage
3,RES-00004,C9751,car-24,Compact,2026-02-04 11:40,05-02-2026 14:40,2026-02-09 12:40,kolkata,22.580673,88.371242,...,4,0,2500,BOGUS99,125.0,2625.0,eco,INVALID,scratch on door,Smooth going
4,RES-00005,C6155,CAR-07,Luxury,2026-02-18 00:59,18/02/2026 08:59,2026-02-21 23:59,Mumbai,19.088202,72.873747,...,1,0,1200/day,BOGUS99,NaN,1260.0,premium,DL12345,Speakers not working,Smooth going

In [3]:
from cleaning import cleaner
from processing import deduplicator
from validation import validator

In [4]:
df["Vehicle_ID"] = df["Vehicle_ID"].apply(cleaner.clean_vehicle_id)
df['Vehicle_ID'].head()

0    CAR-18
1    CAR-12
2    CAR-28
3    CAR-24
4    CAR-07
Name: Vehicle_ID, dtype: str

In [5]:
df["Pickup_TS"] = df["Pickup_TS"].apply(cleaner.clean_timestamp)
df["Return_TS"] = df["Return_TS"].apply(cleaner.clean_timestamp)
df[["Pickup_TS", "Return_TS"]].head()

          Pickup_TS         Return_TS
0  2026-03-23 03:01  2026-03-24 18:01
1  2026-02-27 18:17  2026-03-01 14:17
2  2026-02-28 17:07  2026-03-04 00:07
3  2026-02-05 14:40  2026-02-09 12:40
4  2026-02-18 08:59  2026-02-21 23:59

In [6]:
df.columns

Index(['Reservation_ID', 'Customer_ID', 'Vehicle_ID', 'Vehicle_Class',
       'Booking_TS', 'Pickup_TS', 'Return_TS', 'City', 'Pickup_Lat',
       'Pickup_Lon', 'Drop_Lat', 'Drop_Lon', 'Payment', 'Odo_Start', 'Odo_End',
       'Fuel_Level', 'GPS_Lat', 'GPS_Lon', 'Max_Speed_kmh', 'Harsh_Events',
       'Damage_Flag', 'Rate', 'Promo_Code', 'GST_Amount', 'Total_Amount',
       'Rate_Plan', 'Driver_License', 'Notes', 'Customer_Feedback'],
      dtype='str')

In [7]:
df[["Odo_Start", "Odo_End"]].head()

    Odo_Start    Odo_End
0    30,179km  30,857 km
1     41908km      41829
2  100,504 km  101,678km
3    66,049km  67,079 km
4    41,765km    42647km

In [8]:
df['Odo_Start'] = df['Odo_Start'].apply(cleaner.clean_odometer)
df['Odo_End'] = df['Odo_End'].apply(cleaner.clean_odometer)

df[["Odo_Start", "Odo_End"]].head()

   Odo_Start  Odo_End
0      30179    30857
1      41908    41829
2     100504   101678
3      66049    67079
4      41765    42647

In [9]:
df['Fuel_Level'].head()

0    93 %
1    90 %
2     94%
3      7%
4    0.40
Name: Fuel_Level, dtype: str

In [10]:
df['Fuel_Level'] = df['Fuel_Level'].apply(cleaner.clean_fuel_level)
df['Fuel_Level'].head()

0    0.93
1    0.90
2    0.94
3    0.07
4    0.40
Name: Fuel_Level, dtype: float64

In [11]:
df['Rate'].head()

0    1500/day
1         800
2        2500
3        2500
4    1200/day
Name: Rate, dtype: str

In [12]:
df['Rate'] = df['Rate'].apply(cleaner.clean_rate)
df['Rate'].head()

0    1500
1     800
2    2500
3    2500
4    1200
Name: Rate, dtype: int64

In [13]:
df['City'].head()

0    Kolkata
1      delhi
2    Chennai
3    kolkata
4     Mumbai
Name: City, dtype: str

In [14]:
df['City'] = df['City'].apply(cleaner.clean_city)
df['City'].head()

0    Kolkata
1      Delhi
2    Chennai
3    Kolkata
4     Mumbai
Name: City, dtype: str

In [15]:
df["Reservation_ID"].duplicated().sum()

np.int64(280)

In [16]:
records = df.to_dict(orient="records")

unique_records, duplicates_count = deduplicator.remove_duplicates(records)

print("Duplicates removed:", duplicates_count)

df = pd.DataFrame(unique_records)

df.head()

Duplicates removed: 280

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_TS,Pickup_TS,Return_TS,City,Pickup_Lat,Pickup_Lon,...,Harsh_Events,Damage_Flag,Rate,Promo_Code,GST_Amount,Total_Amount,Rate_Plan,Driver_License,Notes,Customer_Feedback
0,RES-00001,C1434,CAR-18,Luxury,2026-03-22 13:01,2026-03-23 03:01,2026-03-24 18:01,Kolkata,22.576220,88.345171,...,3,0,1500,BOGUS99,75.0,1575.0,standard,INVALID,Scratch on windows,Good mileage
1,RES-00002,C2584,CAR-12,SUV,2026-02-25 11:17,2026-02-27 18:17,2026-03-01 14:17,Delhi,28.690319,77.120789,...,2,0,800,NaN,NaN,840.0,standard,INVALID,Bad Seats Quality,Good mileage
2,RES-00003,C2307,CAR-28,Economy,2026-02-26 18:07,2026-02-28 17:07,2026-03-04 00:07,Chennai,13.090883,80.252533,...,5,0,2500,BOGUS99,NaN,2625.0,eco,DL12345,scratch on door,Good mileage
3,RES-00004,C9751,CAR-24,Compact,2026-02-04 11:40,2026-02-05 14:40,2026-02-09 12:40,Kolkata,22.580673,88.371242,...,4,0,2500,BOGUS99,125.0,2625.0,eco,INVALID,scratch on door,Smooth going
4,RES-00005,C6155,CAR-07,Luxury,2026-02-18 00:59,2026-02-18 08:59,2026-02-21 23:59,Mumbai,19.088202,72.873747,...,1,0,1200,BOGUS99,NaN,1260.0,premium,DL12345,Speakers not working,Smooth going

In [17]:
# df[df["Reservation_ID"].duplicated(keep=False)]

In [18]:
# df = df.drop_duplicates(subset="Reservation_ID", keep="first")

In [19]:
df["Reservation_ID"].duplicated().sum()

np.int64(0)

In [20]:
df.columns

Index(['Reservation_ID', 'Customer_ID', 'Vehicle_ID', 'Vehicle_Class',
       'Booking_TS', 'Pickup_TS', 'Return_TS', 'City', 'Pickup_Lat',
       'Pickup_Lon', 'Drop_Lat', 'Drop_Lon', 'Payment', 'Odo_Start', 'Odo_End',
       'Fuel_Level', 'GPS_Lat', 'GPS_Lon', 'Max_Speed_kmh', 'Harsh_Events',
       'Damage_Flag', 'Rate', 'Promo_Code', 'GST_Amount', 'Total_Amount',
       'Rate_Plan', 'Driver_License', 'Notes', 'Customer_Feedback'],
      dtype='str')

In [21]:
validation_results = df.apply(validator.validate_timestamps, axis=1)

df["timestamp_valid"] = validation_results.apply(lambda x: x[0])
df["timestamp_error"] = validation_results.apply(lambda x: x[1])

In [22]:
# show invalid rows 
df[df["timestamp_valid"] == False][["Pickup_TS","Return_TS","timestamp_error"]]

     Pickup_TS         Return_TS           timestamp_error
33         NaN  2026-02-05 15:27  Unparseable timestamp(s)
171        NaN  2026-01-11 21:06  Unparseable timestamp(s)
554        NaN  2026-03-27 08:25  Unparseable timestamp(s)
693        NaN  2026-01-30 20:56  Unparseable timestamp(s)
788        NaN  2026-02-07 07:07  Unparseable timestamp(s)
...        ...               ...                       ...
6599       NaN  2026-03-06 05:45  Unparseable timestamp(s)
6645       NaN  2026-02-22 00:50  Unparseable timestamp(s)
6715       NaN  2026-01-17 22:21  Unparseable timestamp(s)
6814       NaN  2026-03-11 21:37  Unparseable timestamp(s)
6816       NaN  2026-01-30 12:16  Unparseable timestamp(s)

[64 rows x 3 columns]

In [23]:
#count valid vs invalid 
invalid_ts = df[df["timestamp_valid"] == False]

print("Total records:", len(df))
print("Invalid timestamps:", len(invalid_ts))

invalid_ts.head()

Total records: 7000
Invalid timestamps: 64

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_TS,Pickup_TS,Return_TS,City,Pickup_Lat,Pickup_Lon,...,Rate,Promo_Code,GST_Amount,Total_Amount,Rate_Plan,Driver_License,Notes,Customer_Feedback,timestamp_valid,timestamp_error
33,RES-00034,C7455,CAR-19,Economy,2026-01-27 04:27,NaN,2026-02-05 15:27,Kolkata,22.586220,88.380682,...,1200,BOGUS99,NaN,1260.0,premium,DL67543,Scratch on windows,good service,False,Unparseable timestamp(s)
171,RES-00172,C3604,CAR-28,Economy,2026-01-04 14:06,NaN,2026-01-11 21:06,Bengaluru,12.959693,77.602144,...,1200,SAVE10,60.0,1260.0,standard,DL90871,Bad Seats Quality,Good speaker,False,Unparseable timestamp(s)
554,RES-00555,C2468,CAR-25,Luxury,2026-03-20 08:25,NaN,2026-03-27 08:25,Delhi,28.710212,77.097515,...,2000,BOGUS99,100.0,2100.0,eco,DL90871,Contact Rahul 9876543210,email test@gmail.com,False,Unparseable timestamp(s)
693,RES-00694,C3735,CAR-03,Luxury,2026-01-24 19:56,NaN,2026-01-30 20:56,Chennai,13.092414,80.255756,...,2500,DISC15,125.0,2625.0,premium,DL67543,Scratch on windows,good service,False,Unparseable timestamp(s)
788,RES-00789,C5926,CAR-08,Luxury,2026-01-31 12:07,NaN,2026-02-07 07:07,Bengaluru,12.966016,77.586999,...,3000,DISC15,150.0,3150.0,standard,INVALID,scratch on door,Good mileage,False,Unparseable timestamp(s)

In [24]:
df['Payment']

0          upi
1          UPI
2         card
3         card
4       wallet
         ...
6995      cash
6996      card
6997       upi
6998       upi
6999      cash
Name: Payment, Length: 7000, dtype: str

In [25]:
df['Payment'] = df['Payment'].apply(cleaner.clean_payment)
df['Payment']

0          UPI
1          UPI
2         CARD
3         CARD
4       WALLET
         ...
6995      CASH
6996      CARD
6997       UPI
6998       UPI
6999      CASH
Name: Payment, Length: 7000, dtype: str

In [26]:
df[["Odo_Start", "Odo_End"]]

      Odo_Start  Odo_End
0         30179    30857
1         41908    41829
2        100504   101678
3         66049    67079
4         41765    42647
...         ...      ...
6995      17666    17795
6996      25239    25558
6997     100059   100441
6998      99438   100933
6999      21436    22138

[7000 rows x 2 columns]

In [27]:
results = df.apply(validator.validate_odometer, axis = 1)

df["odometer_valid"] = results.apply(lambda x: x[0])
df["odometer_error"] = results.apply(lambda x: x[1])

In [28]:
df[df["odometer_valid"] == False][["Odo_Start","Odo_End","odometer_error"]]

      Odo_Start  Odo_End                         odometer_error
1         41908    41829    Odo_End (41829) < Odo_Start (41908)
15        73899    73816    Odo_End (73816) < Odo_Start (73899)
22        12781    12400    Odo_End (12400) < Odo_Start (12781)
46        30359    29976    Odo_End (29976) < Odo_Start (30359)
50       113324   113233  Odo_End (113233) < Odo_Start (113324)
...         ...      ...                                    ...
6859      62317    61928    Odo_End (61928) < Odo_Start (62317)
6925      85035    84901    Odo_End (84901) < Odo_Start (85035)
6942      75999    75635    Odo_End (75635) < Odo_Start (75999)
6949       8975     8569      Odo_End (8569) < Odo_Start (8975)
6952      29926    29864    Odo_End (29864) < Odo_Start (29926)

[344 rows x 3 columns]

In [29]:
df["odometer_valid"].value_counts()

odometer_valid
True     6656
False     344
Name: count, dtype: int64

In [30]:
# scenario 11 and 19

from analytics.transformer import compute_record_metrics

In [31]:
df[[
    "Odo_Start",
    "Odo_End",
    "Fuel_Level",
    "Rate",
    "Pickup_TS",
    "Return_TS"
]].head()

   Odo_Start  Odo_End  Fuel_Level  Rate         Pickup_TS         Return_TS
0      30179    30857        0.93  1500  2026-03-23 03:01  2026-03-24 18:01
1      41908    41829        0.90   800  2026-02-27 18:17  2026-03-01 14:17
2     100504   101678        0.94  2500  2026-02-28 17:07  2026-03-04 00:07
3      66049    67079        0.07  2500  2026-02-05 14:40  2026-02-09 12:40
4      41765    42647        0.40  1200  2026-02-18 08:59  2026-02-21 23:59

In [32]:
df_after = df.apply(
    lambda row: compute_record_metrics(row.to_dict()),
    axis=1
)

df_after = pd.DataFrame(df_after.tolist())

In [33]:
df_after[[
    "Odo_Start",
    "Odo_End",
    "Distance_km",
    "Fuel_Level",
    "Refuel_Event",
    "Rate",
    "Rate_Plan",
    "Cost_per_km"
]].head()

,Odo_Start,Odo_End,Distance_km,Fuel_Level,Refuel_Event,Rate,Rate_Plan,Cost_per_km
0,30179,30857,678,0.93,True,1500,standard,2.21
1,41908,41829,0,0.90,False,800,standard,0.00
2,100504,101678,1174,0.94,True,2500,eco,2.13
3,66049,67079,1030,0.07,False,2500,eco,2.43
4,41765,42647,882,0.40,False,1200,premium,1.36

In [34]:
records = df.to_dict(orient="records")
overlapping_ids = deduplicator.detect_overlapping_bookings(records)

print("Overlapping Reservations:", overlapping_ids)
print("Total overlaps detected:", len(overlapping_ids))

Overlapping Reservations: {'RES-03932', 'RES-01319', 'RES-01999', 'RES-06142', 'RES-00549', 'RES-03587', 'RES-05380', 'RES-03388', 'RES-03560', 'RES-06688', 'RES-05979', 'RES-03947', 'RES-05147', 'RES-01193', 'RES-04163', 'RES-06730', 'RES-02239', 'RES-00159', 'RES-04573', 'RES-02183', 'RES-04652', 'RES-03696', 'RES-05956', 'RES-05073', 'RES-05082', 'RES-06939', 'RES-00929', 'RES-06456', 'RES-01269', 'RES-02676', 'RES-04120', 'RES-03861', 'RES-01284', 'RES-06067', 'RES-00432', 'RES-05716', 'RES-00349', 'RES-00808', 'RES-01238', 'RES-06085', 'RES-03959', 'RES-00991', 'RES-06452', 'RES-06945', 'RES-03335', 'RES-03724', 'RES-03053', 'RES-04790', 'RES-02535', 'RES-01964', 'RES-01087', 'RES-04604', 'RES-02439', 'RES-00574', 'RES-02915', 'RES-04365', 'RES-04082', 'RES-02970', 'RES-06241', 'RES-06640', 'RES-01367', 'RES-02247', 'RES-02986', 'RES-05235', 'RES-05109', 'RES-00203', 'RES-06889', 'RES-06994', 'RES-01820', 'RES-04955', 'RES-05756', 'RES-05452', 'RES-04285', 'RES-02601', 'RES-06014', 'RES-06421', 'RES-03654', 'RES-02897', 'RES-03157', 'RES-00119', 'RES-05776', 'RES-00510', 'RES-02125', 'RES-01779', 'RES-01213', 'RES-06115', 'RES-00293', 'RES-00490', 'RES-05543', 'RES-00705', 'RES-05239', 'RES-01608', 'RES-06006', 'RES-01049', 'RES-03298', 'RES-06337', 'RES-02207', 'RES-03751', 'RES-05359', 'RES-01161', 'RES-01370', 'RES-02261', 'RES-05422', 'RES-02934', 'RES-00900', 'RES-01258', 'RES-03400', 'RES-05195', 'RES-05381', 'RES-01758', 'RES-00723', 'RES-03040', 'RES-04362', 'RES-03537', 'RES-03025', 'RES-03989', 'RES-00434', 'RES-06479', 'RES-04589', 'RES-01604', 'RES-04044', 'RES-05428', 'RES-03957', 'RES-06056', 'RES-04977', 'RES-01499', 'RES-02450', 'RES-06229', 'RES-03531', 'RES-06144', 'RES-06878', 'RES-05638', 'RES-04098', 'RES-00039', 'RES-04011', 'RES-01411', 'RES-05363', 'RES-04270', 'RES-04540', 'RES-01197', 'RES-02399', 'RES-04357', 'RES-05841', 'RES-01395', 'RES-01533', 'RES-02798', 'RES-01654', 'RES-00158', 'RES-05153', 'RES-06435', 'RES-00065', 'RES-03912', 'RES-02717', 'RES-05988', 'RES-04684', 'RES-03144', 'RES-06517', 'RES-04575', 'RES-06932', 'RES-00708', 'RES-00315', 'RES-00360', 'RES-05944', 'RES-03222', 'RES-06482', 'RES-06812', 'RES-00080', 'RES-05685', 'RES-04500', 'RES-00002', 'RES-00193', 'RES-00878', 'RES-02615', 'RES-00557', 'RES-06709', 'RES-06820', 'RES-01517', 'RES-00556', 'RES-00693', 'RES-00892', 'RES-00783', 'RES-00910', 'RES-03566', 'RES-04379', 'RES-06420', 'RES-02722', 'RES-04892', 'RES-03078', 'RES-01128', 'RES-04405', 'RES-02885', 'RES-06213', 'RES-05346', 'RES-06417', 'RES-01601', 'RES-06002', 'RES-01524', 'RES-03202', 'RES-02929', 'RES-03528', 'RES-01077', 'RES-00934', 'RES-03647', 'RES-03060', 'RES-05169', 'RES-00048', 'RES-05938', 'RES-04494', 'RES-01786', 'RES-05036', 'RES-04714', 'RES-03037', 'RES-02863', 'RES-02031', 'RES-02255', 'RES-05281', 'RES-01290', 'RES-00534', 'RES-01699', 'RES-00063', 'RES-04501', 'RES-02345', 'RES-01288', 'RES-00323', 'RES-03350', 'RES-03836', 'RES-02340', 'RES-00143', 'RES-00179', 'RES-05822', 'RES-00411', 'RES-03415', 'RES-00435', 'RES-04296', 'RES-00134', 'RES-04982', 'RES-00822', 'RES-05044', 'RES-06795', 'RES-04277', 'RES-01672', 'RES-06821', 'RES-05746', 'RES-04065', 'RES-00653', 'RES-06494', 'RES-05530', 'RES-00785', 'RES-04059', 'RES-04162', 'RES-00416', 'RES-04935', 'RES-05364', 'RES-04614', 'RES-06511', 'RES-04255', 'RES-03396', 'RES-06227', 'RES-03493', 'RES-03843', 'RES-02379', 'RES-05162', 'RES-03276', 'RES-05434', 'RES-05515', 'RES-06644', 'RES-05328', 'RES-03982', 'RES-05976', 'RES-01715', 'RES-05907', 'RES-05062', 'RES-06303', 'RES-01548', 'RES-01115', 'RES-06294', 'RES-03414', 'RES-05789', 'RES-01981', 'RES-01763', 'RES-06761', 'RES-00953', 'RES-05950', 'RES-00735', 'RES-02961', 'RES-03527', 'RES-00463', 'RES-00666', 'RES-02810', 'RES-05095', 'RES-04235', 'RES-03855', 'RES-03703', 'RES-00813', 'RES-02163', 'RES-00258', 'RES-06562', 'RES-00061', 'RES-06011', 'RES-05948', 'RES-06837', 'RES-06360', 'RES-04141', 'RES-06665', 'RES-05031', 'RES-01618', 'RES-02363', 'RES-04015', 'RES-00986', 'RES-00712', 'RES-05886', 'RES-04471', 'RES-00359', 'RES-02889', 'RES-02432', 'RES-05333', 'RES-04337', 'RES-04280', 'RES-02059', 'RES-05748', 'RES-00015', 'RES-01919', 'RES-00883', 'RES-04102', 'RES-06480', 'RES-06834', 'RES-05045', 'RES-06304', 'RES-03966', 'RES-01992', 'RES-04647', 'RES-01619', 'RES-03194', 'RES-00386', 'RES-04320', 'RES-01504', 'RES-01323', 'RES-05497', 'RES-04203', 'RES-02708', 'RES-00683', 'RES-00484', 'RES-04718', 'RES-00610', 'RES-02449', 'RES-04027', 'RES-04358', 'RES-05113', 'RES-03588', 'RES-00811', 'RES-05372', 'RES-06369', 'RES-01726', 'RES-01831', 'RES-03455', 'RES-02393', 'RES-04612', 'RES-00640', 'RES-06505', 'RES-05547', 'RES-04137', 'RES-01123', 'RES-00410', 'RES-03972', 'RES-02925', 'RES-03699', 'RES-03741', 'RES-03536', 'RES-05771', 'RES-02033', 'RES-05504', 'RES-04328', 'RES-01741', 'RES-01979', 'RES-02790', 'RES-01535', 'RES-02401', 'RES-05936', 'RES-05415', 'RES-02189', 'RES-04571', 'RES-07000', 'RES-02528', 'RES-05450', 'RES-02759', 'RES-00964', 'RES-03314', 'RES-06026', 'RES-03004', 'RES-03338', 'RES-06969', 'RES-00177', 'RES-06585', 'RES-05009', 'RES-00499', 'RES-04686', 'RES-01472', 'RES-01774', 'RES-02858', 'RES-06833', 'RES-03499', 'RES-00636', 'RES-05772', 'RES-03994', 'RES-04749', 'RES-06749', 'RES-02748', 'RES-04621', 'RES-03572', 'RES-06592', 'RES-02880', 'RES-04271', 'RES-00958', 'RES-02656', 'RES-04461', 'RES-02414', 'RES-04381', 'RES-04246', 'RES-04026', 'RES-06292', 'RES-00831', 'RES-06706', 'RES-04752', 'RES-04167', 'RES-04942', 'RES-04853', 'RES-04563', 'RES-01048', 'RES-04477', 'RES-05797', 'RES-04333', 'RES-06114', 'RES-00036', 'RES-06675', 'RES-05377', 'RES-01551', 'RES-03113', 'RES-06416', 'RES-04969', 'RES-03066', 'RES-02052', 'RES-00677', 'RES-05615', 'RES-03716', 'RES-02159', 'RES-03551', 'RES-02482', 'RES-06953', 'RES-02012', 'RES-01046', 'RES-00356', 'RES-00335', 'RES-04247', 'RES-02250', 'RES-04618', 'RES-00744', 'RES-03856', 'RES-01267', 'RES-05026', 'RES-04183', 'RES-00414', 'RES-06499', 'RES-00178', 'RES-02234', 'RES-06076', 'RES-05891', 'RES-01502', 'RES-00894', 'RES-06828', 'RES-00022', 'RES-05954', 'RES-02594', 'RES-00139', 'RES-04585', 'RES-00997', 'RES-00148', 'RES-01908', 'RES-02544', 'RES-02434', 'RES-02091', 'RES-00032', 'RES-05426', 'RES-00230', 'RES-06439', 'RES-01506', 'RES-06203', 'RES-02848', 'RES-01657', 'RES-01667', 'RES-00796', 'RES-02991', 'RES-03109', 'RES-00448', 'RES-06175', 'RES-06355', 'RES-03929', 'RES-00224', 'RES-00007', 'RES-01678', 'RES-03904', 'RES-00053', 'RES-04237', 'RES-05745', 'RES-03189', 'RES-03383', 'RES-06198', 'RES-04353', 'RES-06315', 'RES-02521', 'RES-00738', 'RES-03774', 'RES-03514', 'RES-00795', 'RES-03301', 'RES-05049', 'RES-00546', 'RES-04672', 'RES-04528', 'RES-05599', 'RES-02559', 'RES-04204', 'RES-02205', 'RES-04693', 'RES-04737', 'RES-05303', 'RES-02721', 'RES-04816', 'RES-04873', 'RES-00477', 'RES-00283', 'RES-00319', 'RES-03615', 'RES-01731', 'RES-03490', 'RES-03009', 'RES-02324', 'RES-02362', 'RES-01435', 'RES-03482', 'RES-03183', 'RES-04192', 'RES-01231', 'RES-04008', 'RES-06366', 'RES-05070', 'RES-02275', 'RES-03954', 'RES-01062', 'RES-06383', 'RES-01403', 'RES-00939', 'RES-04493', 'RES-01571', 'RES-01154', 'RES-01611', 'RES-05813', 'RES-04349', 'RES-03324', 'RES-04004', 'RES-01419', 'RES-04380', 'RES-01212', 'RES-04492', 'RES-04894', 'RES-06919', 'RES-03322', 'RES-04332', 'RES-04974', 'RES-02911', 'RES-06079', 'RES-05046', 'RES-04995', 'RES-03444', 'RES-01900', 'RES-04666', 'RES-06971', 'RES-02971', 'RES-02150', 'RES-00598', 'RES-06626', 'RES-02500', 'RES-03676', 'RES-00764', 'RES-00047', 'RES-05792', 'RES-04283', 'RES-03885', 'RES-06923', 'RES-06864', 'RES-00710', 'RES-01837', 'RES-01507', 'RES-03892', 'RES-00206', 'RES-04983', 'RES-00025', 'RES-02198', 'RES-02081', 'RES-06636', 'RES-04895', 'RES-04157', 'RES-05903', 'RES-06123', 'RES-02196', 'RES-04470', 'RES-01379', 'RES-06684', 'RES-00161', 'RES-04830', 'RES-00868', 'RES-04419', 'RES-06189', 'RES-03169', 'RES-06386', 'RES-03765', 'RES-03430', 'RES-00282', 'RES-01072', 'RES-04584', 'RES-04579', 'RES-01925', 'RES-04219', 'RES-05691', 'RES-06886', 'RES-05603', 'RES-02804', 'RES-05324', 'RES-01023', 'RES-04826', 'RES-03576', 'RES-01920', 'RES-00250', 'RES-01386', 'RES-00684', 'RES-06840', 'RES-03582', 'RES-04376', 'RES-02694', 'RES-04434', 'RES-01612', 'RES-00586', 'RES-05163', 'RES-05275', 'RES-05406', 'RES-03778', 'RES-02629', 'RES-05966', 'RES-06160', 'RES-01523', 'RES-02396', 'RES-01887', 'RES-05977', 'RES-04046', 'RES-01175', 'RES-02381', 'RES-04489', 'RES-01190', 'RES-03568', 'RES-04638', 'RES-04292', 'RES-02628', 'RES-03730', 'RES-03806', 'RES-00070', 'RES-05116', 'RES-01114', 'RES-02590', 'RES-05124', 'RES-03080', 'RES-06475', 'RES-01282', 'RES-02290', 'RES-04135', 'RES-05353', 'RES-01739', 'RES-06581', 'RES-01871', 'RES-01353', 'RES-02787', 'RES-00182', 'RES-00650', 'RES-01986', 'RES-04068', 'RES-03209', 'RES-01563', 'RES-01838', 'RES-01043', 'RES-02738', 'RES-03893', 'RES-02235', 'RES-02223', 'RES-06008', 'RES-04608', 'RES-06055', 'RES-00144', 'RES-00915', 'RES-00338', 'RES-00424', 'RES-06097', 'RES-04819', 'RES-05002', 'RES-03111', 'RES-06788', 'RES-05928', 'RES-04050', 'RES-04660', 'RES-03653', 'RES-03857', 'RES-04758', 'RES-00049', 'RES-04787', 'RES-02701', 'RES-01064', 'RES-01189', 'RES-03817', 'RES-00441', 'RES-01250', 'RES-02493', 'RES-00846', 'RES-06802', 'RES-01296', 'RES-01251', 'RES-06757', 'RES-04720', 'RES-01076', 'RES-01170', 'RES-04197', 'RES-02686', 'RES-01826', 'RES-06443', 'RES-04171', 'RES-00865', 'RES-01473', 'RES-02875', 'RES-01401', 'RES-00339', 'RES-00502', 'RES-02342', 'RES-01808', 'RES-02043', 'RES-02300', 'RES-00941', 'RES-04061', 'RES-01358', 'RES-04789', 'RES-05039', 'RES-05503', 'RES-04545', 'RES-02305', 'RES-05358', 'RES-04057', 'RES-05629', 'RES-06398', 'RES-05652', 'RES-03764', 'RES-03643', 'RES-04697', 'RES-00342', 'RES-05348', 'RES-04463', 'RES-06365', 'RES-05023', 'RES-03555', 'RES-03156', 'RES-01361', 'RES-05909', 'RES-02690', 'RES-01821', 'RES-06950', 'RES-06622', 'RES-04785', 'RES-05598', 'RES-02391', 'RES-02266', 'RES-06933', 'RES-05729', 'RES-00925', 'RES-00597', 'RES-03592', 'RES-04002', 'RES-04369', 'RES-02854', 'RES-05285', 'RES-00276', 'RES-06631', 'RES-04389', 'RES-03979', 'RES-01844', 'RES-04891', 'RES-06691', 'RES-04893', 'RES-03607', 'RES-01032', 'RES-03634', 'RES-03307', 'RES-02060', 'RES-01176', 'RES-04938', 'RES-03174', 'RES-00028', 'RES-00658', 'RES-05964', 'RES-05540', 'RES-04668', 'RES-01277', 'RES-00496', 'RES-00147', 'RES-04837', 'RES-04804', 'RES-06267', 'RES-00052', 'RES-01534', 'RES-02630', 'RES-04966', 'RES-05736', 'RES-03150', 'RES-03758', 'RES-00168', 'RES-04089', 'RES-06418', 'RES-02895', 'RES-01274', 'RES-05978', 'RES-03739', 'RES-05096', 'RES-02442', 'RES-06557', 'RES-06771', 'RES-01119', 'RES-02826', 'RES-06975', 'RES-01344', 'RES-04022', 'RES-02095', 'RES-06074', 'RES-00631', 'RES-03378', 'RES-01438', 'RES-06999', 'RES-04086', 'RES-06610', 'RES-03085', 'RES-04385', 'RES-01156', 'RES-00584', 'RES-00711', 'RES-06003', 'RES-03978', 'RES-06041', 'RES-04912', 'RES-01592', 'RES-05246', 'RES-00166', 'RES-01789', 'RES-00918', 'RES-00020', 'RES-03625', 'RES-03937', 'RES-04136', 'RES-01873', 'RES-03432', 'RES-05654', 'RES-02175', 'RES-01111', 'RES-01644', 'RES-00922', 'RES-04038', 'RES-00184', 'RES-01220', 'RES-04874', 'RES-04290', 'RES-01564', 'RES-06659', 'RES-00858', 'RES-06843', 'RES-04229', 'RES-05267', 'RES-05501', 'RES-02904', 'RES-02462', 'RES-01800', 'RES-00275', 'RES-05882', 'RES-06905', 'RES-05923', 'RES-05213', 'RES-06507', 'RES-01001', 'RES-06880', 'RES-00089', 'RES-05295', 'RES-04184', 'RES-03357', 'RES-06118', 'RES-00325', 'RES-04533', 'RES-03278', 'RES-02673', 'RES-04063', 'RES-02679', 'RES-03849', 'RES-03445', 'RES-06329', 'RES-04018', 'RES-03729', 'RES-03409', 'RES-00931', 'RES-03227', 'RES-00327', 'RES-04981', 'RES-05467', 'RES-02157', 'RES-04634', 'RES-01519', 'RES-04843', 'RES-04701', 'RES-02665', 'RES-00270', 'RES-02974', 'RES-00603', 'RES-00088', 'RES-00298', 'RES-03931', 'RES-05812', 'RES-06765', 'RES-05157', 'RES-06087', 'RES-00856', 'RES-00923', 'RES-04445', 'RES-03124', 'RES-04842', 'RES-06710', 'RES-04939', 'RES-00300', 'RES-04121', 'RES-01790', 'RES-02461', 'RES-00612', 'RES-06432', 'RES-02997', 'RES-06458', 'RES-05522', 'RES-00988', 'RES-05521', 'RES-05580', 'RES-03804', 'RES-02770', 'RES-00576', 'RES-03773', 'RES-05234', 'RES-00423', 'RES-01166', 'RES-04377', 'RES-05757', 'RES-05773', 'RES-03351', 'RES-01650', 'RES-06759', 'RES-00571', 'RES-01836', 'RES-04708', 'RES-03062', 'RES-05539', 'RES-06403', 'RES-02076', 'RES-00798', 'RES-01891', 'RES-00426', 'RES-01047', 'RES-01389', 'RES-04190', 'RES-02112', 'RES-04616', 'RES-05842', 'RES-04323', 'RES-02296', 'RES-02090', 'RES-03477', 'RES-05378', 'RES-00024', 'RES-05692', 'RES-01320', 'RES-04773', 'RES-01855', 'RES-03138', 'RES-04069', 'RES-04716', 'RES-03207', 'RES-03733', 'RES-06422', 'RES-05139', 'RES-03255', 'RES-04675', 'RES-03328', 'RES-03673', 'RES-05078', 'RES-02376', 'RES-03481', 'RES-02357', 'RES-01508', 'RES-00954', 'RES-01747', 'RES-02944', 'RES-02371', 'RES-01754', 'RES-02581', 'RES-05576', 'RES-06687', 'RES-05280', 'RES-03352', 'RES-02795', 'RES-00719', 'RES-04794', 'RES-04835', 'RES-02647', 'RES-04454', 'RES-05754', 'RES-00318', 'RES-03008', 'RES-00243', 'RES-04899', 'RES-01582', 'RES-06846', 'RES-00180', 'RES-03712', 'RES-02120', 'RES-00553', 'RES-02049', 'RES-00141', 'RES-04645', 'RES-02873', 'RES-03832', 'RES-02092', 'RES-04581', 'RES-02400', 'RES-06288', 'RES-04961', 'RES-01138', 'RES-03219', 'RES-02504', 'RES-01605', 'RES-03969', 'RES-06239', 'RES-00470', 'RES-05312', 'RES-03214', 'RES-00121', 'RES-02263', 'RES-05238', 'RES-00474', 'RES-05744', 'RES-00189', 'RES-06471', 'RES-01634', 'RES-02123', 'RES-00647', 'RES-04580', 'RES-00249', 'RES-01565', 'RES-01957', 'RES-04851', 'RES-00142', 'RES-02608', 'RES-03440', 'RES-06270', 'RES-04195', 'RES-03620', 'RES-03026', 'RES-03541', 'RES-04087', 'RES-02108', 'RES-02965', 'RES-05484', 'RES-05271', 'RES-04778', 'RES-02479', 'RES-06881', 'RES-00350', 'RES-04595', 'RES-04882', 'RES-03502', 'RES-02618', 'RES-04713', 'RES-05343', 'RES-00853', 'RES-03715', 'RES-05807', 'RES-04872', 'RES-06580', 'RES-00726', 'RES-00150', 'RES-05902', 'RES-03027', 'RES-05940', 'RES-06885', 'RES-06520', 'RES-04534', 'RES-05066', 'RES-03475', 'RES-02561', 'RES-03814', 'RES-03564', 'RES-03990', 'RES-01557', 'RES-02733', 'RES-06107', 'RES-02515', 'RES-06572', 'RES-03003', 'RES-04940', 'RES-01939', 'RES-06831', 'RES-03212', 'RES-04917', 'RES-00880', 'RES-00035', 'RES-05012', 'RES-00887', 'RES-06392', 'RES-03001', 'RES-01681', 'RES-00955', 'RES-06415', 'RES-05796', 'RES-01544', 'RES-00774', 'RES-00840', 'RES-06325', 'RES-03485', 'RES-03650', 'RES-05253', 'RES-01245', 'RES-04411', 'RES-01098', 'RES-02855', 'RES-00322', 'RES-05816', 'RES-04155', 'RES-01030', 'RES-01886', 'RES-01152', 'RES-04687', 'RES-00966', 'RES-06990', 'RES-04211', 'RES-01538', 'RES-06271', 'RES-02397', 'RES-04676', 'RES-02603', 'RES-02424', 'RES-01273', 'RES-06532', 'RES-00136', 'RES-03428', 'RES-05922', 'RES-04544', 'RES-03135', 'RES-04945', 'RES-04391', 'RES-01346', 'RES-01649', 'RES-03260', 'RES-02809', 'RES-03632', 'RES-00692', 'RES-03960', 'RES-03756', 'RES-00829', 'RES-03423', 'RES-06750', 'RES-03023', 'RES-06252', 'RES-05102', 'RES-01514', 'RES-04020', 'RES-01223', 'RES-01460', 'RES-04805', 'RES-01761', 'RES-02472', 'RES-06036', 'RES-05585', 'RES-05645', 'RES-00064', 'RES-06526', 'RES-03316', 'RES-05098', 'RES-01131', 'RES-06201', 'RES-02794', 'RES-04593', 'RES-01089', 'RES-05990', 'RES-02737', 'RES-02760', 'RES-00784', 'RES-00364', 'RES-02169', 'RES-05166', 'RES-04674', 'RES-03426', 'RES-00062', 'RES-04962', 'RES-00167', 'RES-05261', 'RES-01850', 'RES-02321', 'RES-04763', 'RES-05969', 'RES-00337', 'RES-04775', 'RES-06277', 'RES-05014', 'RES-03371', 'RES-04386', 'RES-03749', 'RES-02563', 'RES-01139', 'RES-05548', 'RES-00942', 'RES-02476', 'RES-00824', 'RES-03867', 'RES-04218', 'RES-03016', 'RES-01057', 'RES-02715', 'RES-03122', 'RES-04450', 'RES-00834', 'RES-01486', 'RES-01050', 'RES-01383', 'RES-00767', 'RES-04524', 'RES-05847', 'RES-00871', 'RES-06782', 'RES-05516', 'RES-01009', 'RES-05972', 'RES-03199', 'RES-04253', 'RES-04565', 'RES-04926', 'RES-00358', 'RES-06863', 'RES-00812', 'RES-01335', 'RES-01270', 'RES-03064', 'RES-02726', 'RES-05823', 'RES-03569', 'RES-04522', 'RES-03735', 'RES-00776', 'RES-03056', 'RES-02089', 'RES-04678', 'RES-04112', 'RES-00936', 'RES-02978', 'RES-04710', 'RES-00491', 'RES-00509', 'RES-04262', 'RES-04122', 'RES-04031', 'RES-05787', 'RES-06718', 'RES-06866', 'RES-05642', 'RES-01845', 'RES-00351', 'RES-04433', 'RES-03413', 'RES-05941', 'RES-02330', 'RES-06989', 'RES-03665', 'RES-02073', 'RES-02840', 'RES-04403', 'RES-02151', 'RES-01883', 'RES-04728', 'RES-03272', 'RES-00649', 'RES-04368', 'RES-03811', 'RES-05409', 'RES-06282', 'RES-00802', 'RES-00750', 'RES-01034', 'RES-01680', 'RES-01071', 'RES-00415', 'RES-02884', 'RES-05607', 'RES-03269', 'RES-04519', 'RES-01725', 'RES-04797', 'RES-06220', 'RES-02727', 'RES-01404', 'RES-06071', 'RES-01374', 'RES-00805', 'RES-03389', 'RES-03317', 'RES-02578', 'RES-06664', 'RES-00393', 'RES-05699', 'RES-01216', 'RES-00225', 'RES-06368', 'RES-04702', 'RES-05550', 'RES-05924', 'RES-04150', 'RES-00638', 'RES-06470', 'RES-01272', 'RES-01905', 'RES-02093', 'RES-01446', 'RES-01018', 'RES-06236', 'RES-00855', 'RES-02766', 'RES-03649', 'RES-05728', 'RES-01348', 'RES-00544', 'RES-00583', 'RES-02940', 'RES-03463', 'RES-05794', 'RES-00274', 'RES-05751', 'RES-06492', 'RES-00289', 'RES-01136', 'RES-02587', 'RES-01073', 'RES-00221', 'RES-04658', 'RES-03404', 'RES-05641', 'RES-04308', 'RES-01390', 'RES-03834', 'RES-04208', 'RES-03364', 'RES-01778', 'RES-00413', 'RES-04189', 'RES-00131', 'RES-04694', 'RES-02227', 'RES-03309', 'RES-02963', 'RES-03852', 'RES-04185', 'RES-01226', 'RES-06899', 'RES-01547', 'RES-03829', 'RES-03102', 'RES-01860', 'RES-06699', 'RES-04861', 'RES-06029', 'RES-05083', 'RES-00769', 'RES-06702', 'RES-01653', 'RES-06819', 'RES-01006', 'RES-02903', 'RES-00385', 'RES-01413', 'RES-05781', 'RES-03299', 'RES-06295', 'RES-06925', 'RES-02025', 'RES-00505', 'RES-04310', 'RES-06235', 'RES-00850', 'RES-06798', 'RES-05860', 'RES-06808', 'RES-03908', 'RES-06004', 'RES-04404', 'RES-05919', 'RES-05836', 'RES-03368', 'RES-00689', 'RES-06777', 'RES-06556', 'RES-00479', 'RES-04979', 'RES-03825', 'RES-03155', 'RES-00629', 'RES-06697', 'RES-05376', 'RES-03981', 'RES-01578', 'RES-06766', 'RES-03247', 'RES-06354', 'RES-01785', 'RES-04832', 'RES-05431', 'RES-00507', 'RES-06754', 'RES-03496', 'RES-01664', 'RES-04956', 'RES-05202', 'RES-00279', 'RES-01880', 'RES-00944', 'RES-03661', 'RES-05665', 'RES-05103', 'RES-00027', 'RES-06873', 'RES-00044', 'RES-03875', 'RES-04037', 'RES-01527', 'RES-00014', 'RES-04482', 'RES-02977', 'RES-05436', 'RES-01554', 'RES-04043', 'RES-05228', 'RES-04338', 'RES-03173', 'RES-04269', 'RES-06078', 'RES-05931', 'RES-00223', 'RES-04326', 'RES-06941', 'RES-04356', 'RES-05232', 'RES-05490', 'RES-02572', 'RES-05233', 'RES-04931', 'RES-04548', 'RES-06454', 'RES-00487', 'RES-05080', 'RES-05165', 'RES-04504', 'RES-00517', 'RES-06714', 'RES-06343', 'RES-00564', 'RES-05387', 'RES-06654', 'RES-00870', 'RES-02001', 'RES-06187', 'RES-00914', 'RES-05510', 'RES-04093', 'RES-05199', 'RES-06529', 'RES-05920', 'RES-06310', 'RES-02931', 'RES-00021', 'RES-02133', 'RES-04161', 'RES-00500', 'RES-06363', 'RES-02846', 'RES-04703', 'RES-03558', 'RES-05356', 'RES-04932', 'RES-03506', 'RES-06082', 'RES-05575', 'RES-05879', 'RES-02623', 'RES-02037', 'RES-03133', 'RES-06161', 'RES-00533', 'RES-02006', 'RES-04587', 'RES-04643', 'RES-01944', 'RES-02013', 'RES-04267', 'RES-02850', 'RES-06729', 'RES-00504', 'RES-04779', 'RES-04520', 'RES-01388', 'RES-06769', 'RES-02711', 'RES-02044', 'RES-01733', 'RES-03501', 'RES-05004', 'RES-03743', 'RES-00156', 'RES-01830', 'RES-04610', 'RES-06487', 'RES-04729', 'RES-02898', 'RES-03720', 'RES-00461', 'RES-05991', 'RES-01168', 'RES-04250', 'RES-04474', 'RES-

In [35]:
df["Overlapping_Booking"] = df["Reservation_ID"].isin(overlapping_ids)

In [36]:
df["Overlapping_Booking"].value_counts()

Overlapping_Booking
True     6936
False      64
Name: count, dtype: int64

Interpretation:

The dataset reveals severe fleet scheduling conflicts. This demonstrates the importance of automated overlap detection in fleet management systems.

In [37]:
df["Vehicle_ID"].value_counts().head()

Vehicle_ID
CAR-07    255
CAR-14    251
CAR-03    248
CAR-06    248
CAR-28    246
Name: count, dtype: int64

In [38]:
df[["Notes"]].head(20)

                       Notes
0         Scratch on windows
1          Bad Seats Quality
2            scratch on door
3            scratch on door
4       Speakers not working
5         Scratch on windows
6       Speakers not working
7   Contact Rahul 9876543210
8          Bad Seats Quality
9            scratch on door
10      Speakers not working
11      Speakers not working
12  Contact Rahul 9876543210
13         Bad Seats Quality
14        Scratch on windows
15         Bad Seats Quality
16  Contact Rahul 9876543210
17      Speakers not working
18      Speakers not working
19           scratch on door

In [39]:
df["Damage_Reported"] = df["Notes"].fillna("").apply(cleaner.detect_damage)

In [40]:
df["Damage_Reported"].value_counts()

Damage_Reported
False    4221
True     2779
Name: count, dtype: int64

In [41]:
df[["Notes","Damage_Reported"]].head(10)

                      Notes  Damage_Reported
0        Scratch on windows             True
1         Bad Seats Quality            False
2           scratch on door             True
3           scratch on door             True
4      Speakers not working            False
5        Scratch on windows             True
6      Speakers not working            False
7  Contact Rahul 9876543210            False
8         Bad Seats Quality            False
9           scratch on door             True

In [59]:
df["Driver_License"].head(20)

0     INVAXXXXXXX
1     INVAXXXXXXX
2     DL12XXXXXXX
3     INVAXXXXXXX
4     DL12XXXXXXX
5     DL90XXXXXXX
6     DL90XXXXXXX
7     DL90XXXXXXX
8     DL67XXXXXXX
9     DL67XXXXXXX
10    DL90XXXXXXX
11    DL67XXXXXXX
12    DL90XXXXXXX
13    INVAXXXXXXX
14    DL12XXXXXXX
15    DL67XXXXXXX
16    DL90XXXXXXX
17    DL12XXXXXXX
18    DL12XXXXXXX
19    DL67XXXXXXX
Name: Driver_License, dtype: str

In [60]:
df["Driver_License"] = df["Driver_License"].apply(cleaner.mask_driver_license)
df['Driver_License'].head(10)

0    INVAXXXXXXX
1    INVAXXXXXXX
2    DL12XXXXXXX
3    INVAXXXXXXX
4    DL12XXXXXXX
5    DL90XXXXXXX
6    DL90XXXXXXX
7    DL90XXXXXXX
8    DL67XXXXXXX
9    DL67XXXXXXX
Name: Driver_License, dtype: str

Scenario 15 – Promo Code Validation

This rule verifies that promotional codes applied to reservations are valid and not expired.
It helps prevent revenue leakage caused by outdated or unauthorized promo codes.

In [44]:
df[["Reservation_ID","Promo_Code"]].head(10)

  Reservation_ID Promo_Code
0      RES-00001    BOGUS99
1      RES-00002        NaN
2      RES-00003    BOGUS99
3      RES-00004    BOGUS99
4      RES-00005    BOGUS99
5      RES-00006     DISC15
6      RES-00007    BOGUS99
7      RES-00008        NaN
8      RES-00009    BOGUS99
9      RES-00010     SAVE10

In [45]:
promo_results = df.apply(validator.validate_promo_code, axis=1)
df["Promo_Valid"] = promo_results.apply(lambda x: x[0])
df["Promo_Error"] = promo_results.apply(lambda x: x[1])

df[[
    "Reservation_ID",
    "Promo_Code",
    "Promo_Valid",
    "Promo_Error"
]].head(10)

  Reservation_ID Promo_Code  Promo_Valid                  Promo_Error
0      RES-00001    BOGUS99        False  Invalid promo code: BOGUS99
1      RES-00002        NaN        False      Invalid promo code: NAN
2      RES-00003    BOGUS99        False  Invalid promo code: BOGUS99
3      RES-00004    BOGUS99        False  Invalid promo code: BOGUS99
4      RES-00005    BOGUS99        False  Invalid promo code: BOGUS99
5      RES-00006     DISC15         True
6      RES-00007    BOGUS99        False  Invalid promo code: BOGUS99
7      RES-00008        NaN        False      Invalid promo code: NAN
8      RES-00009    BOGUS99        False  Invalid promo code: BOGUS99
9      RES-00010     SAVE10         True

In [46]:
print("Total reservations:", len(df))
print("Invalid promo codes:", (df["Promo_Valid"] == False).sum())

Total reservations: 7000
Invalid promo codes: 3530

16.

In [47]:
df[["GPS_Lat","GPS_Lon"]].head(10)

     GPS_Lat    GPS_Lon
0  15.505045  85.735340
1  17.102400  80.326587
2  26.900000  81.057810
3  16.360000  86.378700
4  19.917400  87.728123
5  16.701430  72.632598
6  27.180000  76.668783
7  22.660000  80.736100
8  22.049100  85.280652
9  13.088400  78.639600

In [48]:
df["GPS_Lat"] = df["GPS_Lat"].apply(cleaner.smooth_gps)
df["GPS_Lon"] = df["GPS_Lon"].apply(cleaner.smooth_gps)

In [49]:
df[["GPS_Lat","GPS_Lon"]].head(10)

   GPS_Lat  GPS_Lon
0  15.5050  85.7353
1  17.1024  80.3266
2  26.9000  81.0578
3  16.3600  86.3787
4  19.9174  87.7281
5  16.7014  72.6326
6  27.1800  76.6688
7  22.6600  80.7361
8  22.0491  85.2807
9  13.0884  78.6396

17

In [50]:
df['Max_Speed_kmh'].head

<bound method NDFrame.head of 0       165 kmh
1            92
2            85
3            81
4            97
         ...
6995    167 kmh
6996         49
6997         83
6998         53
6999         78
Name: Max_Speed_kmh, Length: 7000, dtype: str>

In [51]:
df['Max_Speed_kmh'] = df['Max_Speed_kmh'].apply(cleaner.normalize_speed)
df['Max_Speed_kmh'].head

<bound method NDFrame.head of 0       165
1        92
2        85
3        81
4        97
       ...
6995    167
6996     49
6997     83
6998     53
6999     78
Name: Max_Speed_kmh, Length: 7000, dtype: int64>

18

In [52]:
df[["Notes","Customer_Feedback"]].head(10)

                      Notes     Customer_Feedback
0        Scratch on windows          Good mileage
1         Bad Seats Quality          Good mileage
2           scratch on door          Good mileage
3           scratch on door          Smooth going
4      Speakers not working          Smooth going
5        Scratch on windows          Smooth going
6      Speakers not working          Smooth going
7  Contact Rahul 9876543210          Good mileage
8         Bad Seats Quality  email test@gmail.com
9           scratch on door          good service

In [53]:
df["Notes"] = df["Notes"].apply(cleaner.redact_pii)
df["Customer_Feedback"] = df["Customer_Feedback"].apply(cleaner.redact_pii)

In [54]:
df[["Notes","Customer_Feedback"]].head(10)

                   Notes Customer_Feedback
0     Scratch on windows      Good mileage
1      Bad Seats Quality      Good mileage
2        scratch on door      Good mileage
3        scratch on door      Smooth going
4   Speakers not working      Smooth going
5     Scratch on windows      Smooth going
6   Speakers not working      Smooth going
7  Contact Rahul [PHONE]      Good mileage
8      Bad Seats Quality     email [EMAIL]
9        scratch on door      good service

In [55]:
df["Notes"].str.contains(r'\d{10}', na=False).sum()

np.int64(0)

20

In [56]:
df[["Reservation_ID","Rate","GST_Amount"]].head(10)

  Reservation_ID  Rate  GST_Amount
0      RES-00001  1500        75.0
1      RES-00002   800         NaN
2      RES-00003  2500         NaN
3      RES-00004  2500       125.0
4      RES-00005  1200         NaN
5      RES-00006  2000       100.0
6      RES-00007  2500       125.0
7      RES-00008  1000        50.0
8      RES-00009  1200         NaN
9      RES-00010  2000       100.0

In [57]:
gst_results = df.apply(validator.validate_gst, axis=1)
df["GST_Valid"] = gst_results.apply(lambda x: x[0])
df["GST_Error"] = gst_results.apply(lambda x: x[1])

In [58]:
df[[
    "Reservation_ID",
    "Rate",
    "GST_Amount",
    "GST_Valid",
    "GST_Error"
]].head(10)

  Reservation_ID  Rate  GST_Amount  GST_Valid GST_Error
0      RES-00001  1500        75.0       True
1      RES-00002   800         NaN       True
2      RES-00003  2500         NaN       True
3      RES-00004  2500       125.0       True
4      RES-00005  1200         NaN       True
5      RES-00006  2000       100.0       True
6      RES-00007  2500       125.0       True
7      RES-00008  1000        50.0       True
8      RES-00009  1200         NaN       True
9      RES-00010  2000       100.0       True